export const CONSTANTS = {
    BASE_URL: process.env.REACT_APP_BASE_URL,
    LANGUAGE:"LANGUAGE",
    ENGLISH:"English",
    DANISH:"Danish",
    NAME:"NAME",
    SUPPLIER:"SUPPLIER",
    UPDATED:"UPDATED",
    DOWNLOAD:"DOWNLOAD",
    DOWNLOAD_DOC:"DOWNLOAD_DOC"
} 

 